
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: Abby2020#
development:
  <<: *default
  database: blog_App_development

test:
  <<: *default
  database: blog_App_test

production:
  <<: *default
  database: blog_App_production

